import Head from 'next/head';
import Web3 from "web3";
import { useState, useEffect } from 'react';
import { Tab } from '@headlessui/react';
import { Fragment } from 'react';
import { loadWeb3, vaultDeposit, approveUSDC } from './utils';

export default function Home() {
  const [amount, setAmount] = useState(0);
  const [web3, setWeb3] = useState([]);

  useEffect(async function () {
    setWeb3(await loadWeb3());
  }, [])


  const handleDeposit = () => {
    vaultDeposit(amount);
  }

  return (
    <div className="container bg-black min-h-screen min-w-full">
      <div className="grid grid-cols-3">
        <div className="col-start-3 flex justify-end pt-6 pr-10">
          <button onClick={loadWeb3} className="bg-yellow-300 text-black font-display font-bold rounded-lg w-36 h-12">Connect Wallet</button>
        </div>
        <div className="col-start-2 col-span-1 py-10 flex justify-center">
          <Head>
            <title>brahma.fi</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/brahma.png" />
          </Head>

          <div className="grid grid-rows-6 grid-flow-col">
            {/* <h1 className="flex justify-center">Home</h1> */}
            <div className="row-start-3 w-100 h-100 row-span-4 bg-white border-2 border-black rounded-lg px-10 pt-12">
              <Tab.Group>
                <Tab.List className="flex justify-center">
                  <Tab as={Fragment}>
                    {({ selected }) => (
                      <button
                        className={
                          selected ? 'bg-yellow-300 text-black font-bold font-display px-4 rounded-lg w-28 h-12 mx-4' : 'bg-white text-black font-bold font-display px-4 rounded-lg w-28 h-12 mx-4'
                        }
                      >
                        Deposit
                      </button>
                    )}
                  </Tab>
                  <Tab as={Fragment}>
                    {({ selected }) => (
                      <button
                        className={
                          selected ? 'bg-yellow-300 text-black font-bold font-display px-4 rounded-lg w-28 h-12 mx-4' : 'bg-white text-black font-bold font-display px-4 rounded-lg w-28 h-12 mx-4'
                        }
                      >
                        Withdraw
                      </button>
                    )}
                  </Tab>
                </Tab.List>
                <Tab.Panels className="flex justify-center pt-10">
                  <Tab.Panel>
                    <p className="ml-40 pb-4 font-display font-bold text-sm">Your balance: {web3[2]}</p>
                    <div className="grid grid-cols-6 justify-items-stretch mb-14">
                      <div className="col-start-1 col-span-6 rounded-lg h-16">
                        <input type="text" className="rounded-lg border border-gray-400 h-full w-full px-2 pl-24" placeholder="Enter the amount in USDC" onChange={e => setAmount(e.target.value)}/>
                        <button onClick={approveUSDC} className="bg-yellow-300 text-black font-bold font-display rounded-lg w-28 h-12 mx-36 mt-20 mb-4 text-sm">Approve</button>
                        <button onClick={handleDeposit} className="bg-yellow-300 text-black font-bold font-display rounded-lg w-28 h-12 mx-36 text-sm">Deposit</button>
                      </div>
                    </div>
                  </Tab.Panel>
                  <Tab.Panel>
                  <p className="ml-40 pb-4 font-display font-bold text-sm">Your position:</p>
                    <div className="grid grid-cols-6 justify-items-stretch mb-14">
                      <form action="post" className="col-start-1 col-span-6 rounded-lg h-16">
                        <input type="text" className="rounded-lg border border-gray-400 h-full w-full px-2 pl-24" placeholder="Enter the amount in USDC"/>
                        <button className="bg-yellow-300 text-black font-bold font-display rounded-lg w-28 h-12 mx-36 mt-20 mb-4 text-sm">Approve</button>
                        <button className="bg-yellow-300 text-black font-bold font-display rounded-lg w-28 h-12 mx-36 text-sm">Withdraw</button>
                      </form>
                    </div>
                  </Tab.Panel>
                </Tab.Panels>
              </Tab.Group>
            </div>
            
          </div>

        </div>
      </div>

    </div>
  )
}
